### GET all characters
http://localhost:3000/api/characters


### POST a character
# @name createVader
POST http://localhost:3000/api/characters
Content-Type: application/json

{
    "name": "Darth Vader",
    "characterClass": 1,
    "items": [1,2],
    "attack": 25,
    "mana": 100,
    "hp": 100,
    "level": 10
}

### ID
@id = {{createVader.response.body.data.id}}

### GET one character
http://localhost:3000/api/characters/{{id}}

### PUT a character
PUT http://localhost:3000/api/characters/{{id}}
Content-Type: application/json

{
  "name": "Anakin Skywalker",
  "characterClass": 4,
  "level": 10,
  "hp": 100,
  "mana": 50,
  "attack": 30,
  "items": [1]
}

### POST a character
POST http://localhost:3000/api/characters
Content-Type: application/json

{
    "name": "Luke Skywalker",
    "characterClass": 3,
    "items": [1],
    "attack": 20,
    "mana": 70,
    "hp": 130,
    "level": 5
}

### POST a character
# @name createCharacterToDelete
POST http://localhost:3000/api/characters
Content-Type: application/json

{
    "name": "Ashoka Tano",
    "characterClass": 3,
    "items": [1],
    "attack": 20,
    "mana": 70,
    "hp": 130,
    "level": 5
}
### DELETE a character
@idToDelete = {{createCharacterToDelete.response.body.data.id}}
DELETE http://localhost:3000/api/characters/{{idToDelete}}

### PATCH a character
PATCH http://localhost:3000/api/characters/{{idToDelete}}
Content-Type: application/json

{
  "level": 6,
  "characterClass":4,
  "items": [1]
}

### DELETE a character
DELETE http://localhost:3000/api/characters/{{idToDelete}}